server:
  port: 8080

spring:
  datasource:
    username: superuser
    password: 80208020
    url: jdbc:postgresql://postgres:5432/search_engine
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    show-sql: false


indexing-settings:
  sites:
    - url: https://sendel.ru/
      name: sendel
    - url: https://www.abri-kos.ru
      name: abrikos
    - url: http://www.playback.ru
      name: playback
    - url: https://volochek.life/
      name: volochek.life
    - url: https://ipfran.ru/
      name: ipfran
    - url: https://dimonvideo.ru/
      name: dimon
    - url: https://dombulgakova.ru/
      name: dom-bulgakova
    - url: https://www.likeservice-tomsk.ru/
      name: like-service
jsoup:
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  referrer: "https://www.example.com"
  sleepPageConnectorBasicVolume: 1000
  sleepPageConnectorAdditionalVolumeRandomTo: 1000
